#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'Publications', url: 'pages/publications.html'}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Nathan C. Hurley MD/PhD Personal Site'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# About Section

about: >
  # Nathan C. Hurley

  Hello! I am an MD/PhD student at Texas A&M University.  I started medical school in Fall 2014, completed my first three years of medical school, and then transitioned to graduate school.  I am aiming to complete my PhD in Computer Science in May 2021, and then I'll return to medical school to complete my MD.  I plan to apply to residency in anesthesia.

contact: >
  # Contact

  You may contact me at nathan \[at\] hurley \[dot\] icu. 


publications: >
  # Publications

  ## 2020

  **Association of Use of an Intravascular Microaxial Left Ventricular Assist Device vs Intra-aortic Balloon Pump With In-Hospital Mortality and Major Bleeding Among Patients With Acute Myocardial Infarction Complicated by Cardiogenic Shock**


  Sanket S Dhruva, Joseph S Ross, Bobak J Mortazavi, *Nathan C Hurley,* Harlan M Krumholz, Jeptha P Curtis, Alyssa Berkowitz, Frederick A Masoudi, John C Messenger, Craig S Parzynski, Che Ngufor, Saket Girotra, Amit P Amin, Nilay D Shah, Nihar R Desai


  *Journal of the American Medical Association*


  [Paper](https://jamanetwork.com/journals/jama/article-abstract/2761003)


  ---


  **A Survey of Challenges and Opportunities in Sensing and Analytics for Risk Factors of Cardiovascular Disorders**


  *Nathan C Hurley,* Erica S Spatz, Harlan M Krumholz, Roozbeh Jafari, Bobak J Mortazavi


  *ACM Transactions on Computing for Healthcare*


  [Paper](http://jafari.tamu.edu/wp-content/uploads/2021/01/A-Survey-of-Challenges-and-Opportunities-in-Sensing-and-Analytics-for-Risk-Factors-of-Cardiovascular-Disorders.pdf)


  ---


  **Dynamically Extracting Outcome-Specific Problem Lists from Clinical Notes with Guided Multi-Headed Attention**


  Justin Lovelace, *Nathan C Hurley,* Adrian D Haimovich, Bobak J Mortazavi


  *Machine Learning for Healthcare Conference*


  [Paper](http://proceedings.mlr.press/v126/lovelace20a/lovelace20a.pdf)


  ---


  **Developing Personalized Models of Blood Pressure Estimation from Wearable Sensors Data Using Minimally-trained Domain Adversarial Neural Networks**


  Lida Zhang, *Nathan C Hurley,* Bassem Ibrahim, Erica Spatz, Harlan M Krumholz, Roozbeh Jafari, Bobak J Mortazavi


  *Machine Learning for Healthcare Conference*


  [Paper](http://proceedings.mlr.press/v126/zhang20a/zhang20a.pdf)


  ---


  **Uncertainty Quantification for Deep Context-Aware Mobile Activity Recognition and Unknown Context Discovery**


  Lida Zhang, *Nathan C Hurley,* Bassem Ibrahim, Erica Spatz, Harlan M Krumholz, Roozbeh Jafari, Bobak J Mortazavi


  *23rd International Conference on Artificial Intelligence and Statistics (AISTATS)*


  [Paper](http://proceedings.mlr.press/v108/huo20a/huo20a.pdf)


  ---


  **Clinical Characteristics and Outcomes for 7,995 Patients with SARS-CoV-2 Infection**


  Jacob McPadden, Frederick Warner, H Patrick Young, *Nathan C Hurley,* Rebecca A Pulk, Avinainder Singh, Thomas JS Durant, Guannan Gong, Nihar Desai, Adrian Haimovich, Richard Andrew Taylor, Murat Gunel, Charles S Dela Cruz, Shelli F Farhadian, Jonathan Siner, Merceditas Villanueva, Keith Churchwell, Allen Hsiao, Charles J Torre Jr, Eric J Velazquez, Roy S Herbst, Akiko Iwasaki, Albert I Ko, Bobak J Mortazavi, Harlan M Krumholz, Wade L Schulz


  *medRxiv*


  [Paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7386526/pdf/nihpp-2020.07.19.20157305.pdf)
  
#-------------------------------
# Work Section

projects:

- {name: 'Curriculum Vitae', folder: 'proj-1', file: 'cv/'}
#- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: '#'}
#- {icon: 'instagram', link: '#'}
- {icon: 'github', link: 'https://github.com/Nathan-C-Hurley'}
#- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:nathan@hurley.icu'}
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=8nHGeIMAAAAJ&hl=en'}
- {icon: 'building', link: 'https://stmi.engr.tamu.edu/people/nate-hurley/'}
- {icon: 'arxiv', link: 'https://arxiv.org/a/hurley_n_1.html'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
