#-------------------------------
# General Site Settings

menu:
#- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Nathan C. Hurley MD/PhD Personal Site'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# About Section

about: >
  # Nathan C. Hurley

  Hello! I am an MD/PhD student at Texas A&M University.  I started medical school in Fall 2014, completed my first three years of medical school, and then transitioned to graduate school.  I am aiming to complete my PhD in Computer Science in May 2021, and then I'll return to medical school to complete my MD.  I plan to apply to residency in anesthesia.

contact: >
  # Contact

  You may contact me at nathan \[at\] hurley \[dot\] icu. 

#-------------------------------
# Work Section

projects:
#- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
#- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: '#'}
#- {icon: 'instagram', link: '#'}
- {icon: 'github', link: 'https://github.com/Nathan-C-Hurley'}
#- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:nathan@hurley.icu'}
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=8nHGeIMAAAAJ&hl=en'}
- {icon: 'building', link: 'https://stmi.engr.tamu.edu/people/nate-hurley/'}
- {icon: 'arxiv', link: 'https://arxiv.org/a/hurley_n_1.html'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
